### ISSUE TITLE
Vebugger splits the buffer on every step over/in

### ISSUE THREAD

**Issue by VermaGa** [idanarye/vim-vebugger#23] opened 2015-11-05 15:39 UTC
the window keeps splitting every time i step over. seems like it opens a new buffer opens every time.

**Comment by idanarye** [comment] 2015-11-06 10:24
Weird. Does the step over/in take you to a line in the same file you were or to a line in another file?

**Comment by VermaGa** [comment] 2015-11-06 12:11
Thanks idanarye.
It is the same file.

 If you think it helps I could share my vimrc and plugins

**Comment by idanarye** [comment] 2015-11-06 13:52
Before we do that, I want to check something else. The `:VBGtoggleTerminalBuffer` opens a buffer where Vebugger prints the raw output of the debugger it operates. Please run it, do a step over/in, and copy what it prints when you do that.

**Comment by VermaGa** [comment] 2015-11-06 16:12
![capture](https://cloud.githubusercontent.com/assets/15673520/11001799/3204ed80-8477-11e5-9149-b64ea26d7e5a.PNG)
Pls see the attachment.

The buffer keeps splitting every time is step

**Comment by idanarye** [comment] 2015-11-06 19:02
OK, the regex in Vebugger's GDB module properly matches that output, so that wasn't the problem. I suspect it fails to detect that the buffer was already loaded.

In `autoload/vebugger/std.vim` in line 171 you should see these lines:

``` vim
            if !bufexists(a:readResult.std.location.file)
                exe get(g:, 'vebugger_view_source_cmd', 'new').' '.(a:readResult.std.location.file)
            endif
```

Please add the following line just before them:

``` vim
echo a:readResult bufname(0) bufexists(a:readResult.std.location.file)
```

This should print, whenever Vebugger is going to jump somewhere, where it thinks it should go, where it thinks it currently is, and whether or not it thinks it's target buffer exists. Please post here with what it prints when you step over/in.

**Comment by VermaGa** [comment] 2015-11-06 19:49
I see something different on 171
169 "Make Vim jump to the currently executed line
170 function! s:standardThinkHandlers.moveToCurrentLine(readResult,debugger) dict
171     if !empty(a:readResult.std.location)
172         if !empty(a:debugger.state.std.config.externalFileStop_flowCommand) " Do we need to worry about stopping at external files?
173             if 0!=stridx(tolower(fnamemodify(a:readResult.std.location.file,':p')),tolower(getcwd()))
174                 call a:debugger.setWriteAction('std','flow',a:debugger.state.std.config.externalFileStop_flowCommand)
175                 return
176             endif
177         endif
178         if a:debugger.state.std.location!=a:readResult.std.location
179             if has_key(a:debugger.state.std.location,'file')
180                 exe 'sign unplace 1 file='.fnameescape(fnamemodify(a:debugger.state.std.location.file,':p'))
181             endif
182             let a:debugger.state.std.location=deepcopy(a:readResult.std.location)
183             if !bufexists(a:readResult.std.location.file)
184                 exe get(g:, 'vebugger_view_source_cmd', 'new').' '.(a:readResult.std.location.file)
185             endif
186             call vebugger#std#updateMarksForFile(a:debugger.state,a:readResult.std.location.file)
187             exe 'sign jump 1 file='.fnameescape(fnamemodify(a:readResult.std.location.file,':p'))
188         endif
189     endif
190 endfunction

**Comment by VermaGa** [comment] 2015-11-06 19:55
{'std': {'location': {'file': '~/filename.cpp', 'line': 48}, 'callstack': {}, 'evaluatedExpression': {}, 'programOutput': {}, 'programFinish': {}, 'exception': {}
}}  0

**Comment by idanarye** [comment] 2015-11-06 19:55
Sorry, I merged a PR using Github's web interface and did not pull to my local copy ever since...

Anyways, now the same code is in line 183, so add it before there.

**Comment by VermaGa** [comment] 2015-11-06 19:56
{'std': {'location': {'file': '~/filename.cpp', 'line': 50}, 'callstack': {}, 'evaluatedExpression': {}, 'programOutput': {}, 'programFinish': {}, 'exception': {}
}}  0

**Comment by idanarye** [comment] 2015-11-06 20:30
OK, assuming the file path really starts with `~/`, I think I know what the problem is. I've just pushed a fix - try it, and reopen this issue if it doesn't fix it for you.

**Closed as completed** 2015-11-06 20:30 UTC
